version: '3'

services:
  postgres:
    volumes:
      - ./tmp/postgres/dev:/var/lib/postgresql/data
    env_file: .env

  backend:
    expose:
      - 3000
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: enabled
      RUBYOPT: -W:no-deprecated
      TERM: xterm-256color
      REDIS_URL: redis://redis:6379/1

  frontend:
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    env_file: .env
    environment:
      TERM: xterm-256color
    command: /bin/sh -c 'npm i && npm run serve'

  frontend_v2:
    ports:
      - 8088:8088
    volumes:
      - ./frontend_v2:/app
    env_file: .env
    environment:
      TERM: xterm-256color
    command: /bin/sh -c 'pnpm i && pnpm run serve'
