version: '3'

services:
  postgres:
    image: postgres:11-alpine
    expose:
      - 5432
    networks:
      - net

  backend:
    build:
      context: .
    image: bankoque_backend
    networks:
      - net
    depends_on:
      - postgres
    working_dir: /app
    command: ./docker-entrypoint.sh
    stop_signal: SIGINT

  frontend:
    build:
      context: ./frontend
    image: bankoque_frontend
    networks:
      - net
    working_dir: /app

networks:
  net:
    ipam:
      driver: default
