version: '3'

services:
  postgres:
    image: postgres:11-alpine
    expose:
      - 5432
    networks:
      - net

  backend:
    build:
      dockerfile: Dockerfile
      context: .
    image: bankoque
    networks:
      - net
    depends_on:
      - postgres
    working_dir: /app
    command: ./docker-entrypoint.sh
    stop_signal: SIGINT

  frontend:
    image: node:12-alpine
    networks:
      - net
    working_dir: /app

networks:
  net:
    ipam:
      driver: default
