services:
  postgres:
    volumes:
      - ./postgres/dev:/var/lib/postgresql/data
    env_file: .env

  backend:
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    env_file: .env

  frontend:
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    env_file: .env
    command: deno task dev
